name: code_check

# Controls when the action will run. 
on:
  push: # push的时候触发
    branches: # 那些分支需要触发
      - master
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check_code:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: Python Pylin GitHub Action
          uses: vcoder4c/git_pylint@v3
          env:
            DEFAULT_TARGET_BRANCH: master
    
