on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to run github action
    steps:
    - name: Run Action Step
      uses: LakshitF/pylint3-action@master
      with:
        filename: './polar'